FROM node:16

LABEL name="Serviço Node para compilar o Angular" \
        version="1.0"

WORKDIR /var/www

COPY ../frontend/ .

RUN apt-get -y update && apt-get -y upgrade
RUN apt-get -y install git

RUN npm uninstall -g angular-cli @angular/cli
RUN npm cache verify
RUN npm i -g @angular/cli@13.1.4
RUN npm install
RUN npm install --arch=x64 --platform=linux sharp

EXPOSE 9090

ENTRYPOINT ["ng", "build"]